name: "Sample #3: DID:web as claim issuer, with document hosted on Github Pages"

on: [push]

env:
  did_web_url: https://ryazhang-microsoft.github.io/.well-known/did.json
  did_web_privk: ${{ secrets.EC_PRIVK }}

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
 
      - name: Generate SBOM 
        run: |
          curl -Lo sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x ./sbom-tool
          ./sbom-tool generate -BuildDropPath . -BuildComponentPath . -PackageName ${{ github.event.repository.name }} -PackageVersion 1.0.0 -PackageSupplier TravisJCo -NamespaceUriBase https://sbom.travisjco.com -V Verbose
          cat _manifest/spdx_2.2/manifest.spdx.json
      
      - name: Install SCITT CLI
        run: |
          tar -xzf linux_amd64.tar.gz
          mv ./linux_amd64/scitt /usr/local/bin
          scitt prepare ./_manifest/spdx_2.2/manifest.spdx.json:application/spdx+json --output SBOMDescriptor.json
          cat ./SBOMDescriptor.json

      - name: did
        run: |
          curl -Lo did.json ${{ env.did_web_url }}
          cat did.json
        
      - name: private key
        run: |
          echo "${{ secrets.EC_PRIVK }}" >> ec_privk.pem
          cat ec_privk.pem

      - name: Install PYSCITT
        run: | 
          git clone https://github.com/microsoft/scitt-ccf-ledger
          cd scitt-ccf-ledger
          pip install --disable-pip-version-check -q -e ./pyscitt          
          scitt sign --claims ../SBOMDescriptor.json --did-doc ../did.json --out ../SBOMDescriptor.cose --key ../ec_privk.pem --content-type "application/json"
          
      - name: Submit Claims by SCITT CLI
        run: |
          scitt        
