name: "Sample #3: DID:web as claim issuer, with document hosted on Github Pages"

on: [push]

env:
  did_web_url: https://ryazhang-microsoft.github.io/.well-known/did.json
  did_web_privk: ${{ secrets.EC_PRIVK }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_GITHUB_CREDS }}
     
      - run: |
          az webapp list --query "[?state=='Running']"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
 
      - name: Generate SBOM 
        run: |
          curl -Lo sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x ./sbom-tool
          ./sbom-tool generate -BuildDropPath . -BuildComponentPath . -PackageName ${{ github.event.repository.name }} -PackageVersion 1.0.0 -PackageSupplier TravisJCo -NamespaceUriBase https://sbom.travisjco.com -V Verbose
      
      - name: Install SCITT CLI And Generate SCITT Prepare File
        run: |
          tar -xzf linux_amd64.tar.gz
          mv ./linux_amd64/scitt /usr/local/bin
          scitt prepare ./_manifest/spdx_2.2/manifest.spdx.json:application/spdx+json --output SBOMDescriptor.json
          cat ./SBOMDescriptor.json

      - name: Download DID Document 
        run: |
          curl -Lo did.json ${{ env.did_web_url }}
          cat did.json
        
      - name: Download Private Key
        run: |
          echo "${{ secrets.EC_PRIVK }}" >> ec_privk.pem

      - name: Install PYSCITT and Sign the SCITT Prepare with Did.json and Private Key 
        run: | 
          git clone https://github.com/microsoft/scitt-ccf-ledger
          cd scitt-ccf-ledger
          ./pyscitt.sh sign --claims ../SBOMDescriptor.json --did-doc ../did.json --out ../SBOMDescriptor.cose --key ../ec_privk.pem --content-type "application/json"
          
      - name: Submit Claims and Verify by SCITT CLI
        run: |
          scitt submit --signature ./SBOMDescriptor.cose --output receipt.scitt --format plainCbor --service-name test
          scitt verify --receipt ./receipt.scitt --signature ./SBOMDescriptor.cose --artifact ./_manifest/spdx_2.2/manifest.spdx.json --service-name test
      
      - name: Publish artifacts and signatures
        uses: actions/upload-artifact@v3.1.1
        with:
          path: |
            _manifest/spdx_2.2/manifest.spdx.json
            SBOMDescriptor.cose
            receipt.scitt
