name: "Sample #3: DID:web as claim issuer, with document hosted on Github Pages"

on: [push]

env:
  did_web_url: https://ryazhang-microsoft.github.io/.well-known/did.json

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Install PYSCITT
        run: | 
          git clone https://github.com/microsoft/scitt-ccf-ledger
          cd scitt-ccf-ledger
          pip install --disable-pip-version-check -q -e ./pyscitt
      
      - name: Install SCITT CLI
        run: |
          wget https://github.com/microsoft/scittcli/releases/download/v1.0.0-alpha.5/linux_arm64.tar.gz
          tar -xzf linux_arm64.tar.gz
          mv ./linux_arm64/scitt /usr/local/bin
     
