name: "Sample #3: DID:web as claim issuer, with document hosted on Github Pages"

on: [push]

env:
  did_web_url: https://ryazhang-microsoft.github.io/.well-known/did.json

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - name: Setup Python
        uses: actions/setup-python@v3.8.0

      - name: Install PYSCITT
        run: | 
          git clone https://github.com/microsoft/scitt-ccf-ledger
          cd scitt-ccf-ledger
          pip install --disable-pip-version-check -q -e ./pyscitt
